# 🌖🌖 Copyright Monwoo 2023 🌖🌖, build by Miguel Monwoo, service@monwoo.com

# Biblio :
# https://turbo.build/repo/docs
# https://turbo.build/repo/docs/getting-started/create-new
# https://turbo.build/pack/docs/roadmap#svelte
# https://vercel.com/templates/svelte/turborepo-sveltekit-starter
# https://dev.to/_gdelgado/pitfalls-when-adding-turborepo-to-your-project-4cel

packages:
  - "apps/*"
  - "apps/mws-sf-pdf-billings/backend"
  - "packages/*"
  - "../mws-demo"
  # Configure the target apps for SF builds (Should change if app target build did change :) :
  # to avoid app dependencies in packages like :
  #  "fos-router": "link:../../apps/mws-sf-pdf-billings/backend/vendor/friendsofsymfony/jsrouting-bundle/Resources",
  - "apps/mws-sf-pdf-billings/backend/vendor/friendsofsymfony/jsrouting-bundle/Resources"
  # "@symfony/ux-svelte": "file:vendor/symfony/ux-svelte/assets",
  # "@symfony/ux-svelte": "file:../../apps/mws-sf-pdf-billings/backend/vendor/symfony/ux-svelte/assets",
  - "apps/mws-sf-pdf-billings/backend/vendor/symfony/ux-svelte/assets"
