

# controllers:
#     # https://symfony.com/doc/current/bundles/override.html
#     resource: ../../../../../packages/mws-moon-manager/src/Controller/
#     # resource: 'MoonManagerBundle/src/Controller'
#     type: annotation
# https://symfonycasts.com/screencast/micro-symfony/app-bundle-annotations
# TODO : auto add from recipe
# TODO : not failing like gphoto routes if no mws demo bundle loaded ? 
#          conditional route on env params ? 
mws_demo:
    resource: "@DemoBundle/src/Controller/"
    # https://stackoverflow.com/questions/48120939/symfony-4-global-route-prefix
    prefix: mws
    type: annotation
    # https://stackoverflow.com/questions/61059875/controller-has-no-container-set-did-you-forget-to-define-it-as-a-service-subscr
    options:
        autowire: true
