when@dev:
    web_profiler_wdt:
        # !!    The function "class_exists" does not exist around position 1 for expression  
        # condition: "class_exists('Symfony\\Bundle\\DebugBundle\\DebugBundle')"
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
        prefix: /_wdt

    web_profiler_profiler:
        # !!    The function "class_exists" does not exist around position 1 for expression  
        # condition: "class_exists('Symfony\\Bundle\\DebugBundle\\DebugBundle')"
        resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
        prefix: /_profiler
