# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    # https://stackoverflow.com/questions/25948853/how-to-install-the-intl-extension-for-twig/28410279#28410279
    default_locale: fr
    serializer:
        circular_reference_handler: 'App\Serializer\CircularReferenceHandler'
        enabled: true
        # https://github.com/symfony/symfony/pull/38542
        default_context:
            # vendor/symfony/serializer/Encoder/YamlEncoder.php:65
            yaml_inline: 7
            # yaml_indent: 2
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
