monolog:
    channels:
      - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        # this "file_log" key could be anything
        file_log:
            # type: stream
            type: rotating_file
            max_files: 30
            # log to var/log/(environment).log
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            # log *all* messages (debug is lowest level)
            level: error
when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: warning
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: warning
                formatter: monolog.formatter.json
            # nested:
            #     type: stream
            #     path: "%kernel.logs_dir%/%kernel.environment%.log"
            #     level: error
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            # deprecation:
            #     type: stream
            #     channels: [deprecation]
            #     path: php://stderr
