# TODO : auto gen from recipe...
parameters:
    # TODO : property access fail ? array hard to handle ?
    # bin/console debug:container --env-vars
    # bin/console debug:container --parameters
    mws_moon_manager.uploadSubFolder: var/uploads
    # # WARNING : using public path need strong security review... :
    # mws_moon_manager.uploadSubFolder: public/uploads
    mws_moon_manager:
        # tips : mws_moon_manager will be array, not 'mws_moon_manager.uploadSubFolder'
        # uploadSubFolder: xxx
        offer:
            defaultTags:
              - label: Prospection
                categoryOkWithMultiplesTags: false
              - label: A relancer
                categorySlug: prospection
              - label: Investir pour relancer
                categorySlug: prospection
              - label: Risque de non-rentabilité
                categorySlug: prospection
              - label: Pas de réponse
                categorySlug: prospection
              - label: Ne veut pas être dérangé
                categorySlug: prospection
              - label: Devis à négocier
                categorySlug: prospection
              - label: En attente de paiement
                categorySlug: prospection
              - label: Synthèse à faire
                categorySlug: prospection
              - label: Validation des suivis
                categorySlug: prospection
              - label: Livraison OK
                categorySlug: prospection
              - label: Hors cible business
                categorySlug: prospection

