# TODO : auto gen from recipe...
parameters:
    # TODO : property access fail ? array hard to handle ?
    # bin/console debug:container --env-vars
    # bin/console debug:container --parameters
    mws_moon_manager.uploadSubFolder: var/uploads
    # # WARNING : using public path need strong security review... :
    # mws_moon_manager.uploadSubFolder: public/uploads
    mws_moon_manager:
        # tips : mws_moon_manager will be array, not 'mws_moon_manager.uploadSubFolder'
        # uploadSubFolder: xxx
        offer:
            defaultTags:
              - label: Prospection
                categoryOkWithMultiplesTags: false
              - label: Prospect à relancer
                categorySlug: prospection
              - label: Investir pour relancer
                categorySlug: prospection
              - label: Risque de non-rentabilité
                categorySlug: prospection
              - label: Pas de réponse
                categorySlug: prospection
              - label: Ne veut pas être dérangé
                categorySlug: prospection
              - label: Prospect à négocier
                categorySlug: prospection
              - label: En attente de paiement
                categorySlug: prospection
              - label: Synthèse à faire
                categorySlug: prospection
              - label: Validation des suivis
                categorySlug: prospection
              - label: Livraison OK
                categorySlug: prospection
              - label: Hors cible business
                categorySlug: prospection
              - label: Analyse
                categoryOkWithMultiplesTags: true
              - label: Pour un partenaire
                categorySlug: analyse
              - label: Nécessite un partenaire
                categorySlug: analyse
              - label: Urgent
                categorySlug: analyse
              - label: Test via téléphone
                categorySlug: analyse
              - label: Test via email
                categorySlug: analyse
              - label: Test via WhatsApp
                categorySlug: analyse
              - label: Test via tchat de l'offre
                categorySlug: analyse
              - label: Test via oral
                categorySlug: analyse
              - label: Ok via téléphone
                categorySlug: analyse
              - label: Ok via email
                categorySlug: analyse
              - label: Ok via WhatsApp
                categorySlug: analyse
              - label: Ok via tchat de l'offre
                categorySlug: analyse
              - label: Ok via oral
                categorySlug: analyse
              - label: Signé par écrit papier
                categorySlug: analyse
              - label: Signé par premier paiement
                categorySlug: analyse
              - label: Signé par acceptation email
                categorySlug: analyse
              - label: Kanban
                categoryOkWithMultiplesTags: false
              - label: Marché
                categorySlug: kanban
              - label: Backlog
                categorySlug: kanban
              - label: A relancer
                categorySlug: kanban
              - label: VIP
                categorySlug: kanban
              - label: Devis à négocier
                categorySlug: kanban
              - label: Devis OK
                categorySlug: kanban
              - label: Devis KO
                categorySlug: kanban
              - label: Meilleur choix Monwoo
                categoryOkWithMultiplesTags: false
              - label: Monwoo 1/5
                categorySlug: meilleur-choix-monwoo
              - label: Monwoo 2/5
                categorySlug: meilleur-choix-monwoo
              - label: Monwoo 3/5
                categorySlug: meilleur-choix-monwoo
              - label: Monwoo 4/5
                categorySlug: meilleur-choix-monwoo
              - label: Monwoo 5/5
                categorySlug: meilleur-choix-monwoo
              - label: Meilleur choix Axelo
                categoryOkWithMultiplesTags: false
              - label: Axelo 1/5
                categorySlug: meilleur-choix-axelo
              - label: Axelo 2/5
                categorySlug: meilleur-choix-axelo
              - label: Axelo 3/5
                categorySlug: meilleur-choix-axelo
              - label: Axelo 4/5
                categorySlug: meilleur-choix-axelo
              - label: Axelo 5/5
                categorySlug: meilleur-choix-axelo
              - label: Meilleur choix Jpsy
                categoryOkWithMultiplesTags: false
              - label: Jpsy 1/5
                categorySlug: meilleur-choix-jpsy
              - label: Jpsy 2/5
                categorySlug: meilleur-choix-jpsy
              - label: Jpsy 3/5
                categorySlug: meilleur-choix-jpsy
              - label: Jpsy 4/5
                categorySlug: meilleur-choix-jpsy
              - label: Jpsy 5/5
                categorySlug: meilleur-choix-jpsy
