twig:
    default_path: '%kernel.project_dir%/templates'
    # https://stackoverflow.com/questions/28872529/get-kernel-root-dir-in-twig-template-with-symfony-2
    globals:
        kernelRootDir: "%kernel.project_dir%"
        # https://ourcodeworld.com/articles/read/1177/how-to-retrieve-env-variables-directly-from-a-twig-view-in-symfony-5
        # TIPS : use '%env(bool:HAVE_MWS_DEMO)%' to avoid error on 'must be string' from env...
        HAVE_MWS_DEMO: '%env(bool:HAVE_MWS_DEMO)%'
        # TODO : tips : below not needed, all env var injected
        #               by which other way ?
        CONFIG_BCKUP_MAX_UPLOAD_SIZE: '%env(CONFIG_BCKUP_MAX_UPLOAD_SIZE)%'
    number_format:
        decimals: 4
    # https://symfony.com/doc/current/the-fast-track/en/22-encore.html#leveraging-bootstrap
    # https://symfony.com/doc/current/form/tailwindcss.html
    form_themes: ['tailwind_2_layout.html.twig']

when@test:
    twig:
        strict_variables: true
