twig:
    default_path: '%kernel.project_dir%/templates'
    # https://stackoverflow.com/questions/28872529/get-kernel-root-dir-in-twig-template-with-symfony-2
    globals:
        kernelRootDir: "%kernel.project_dir%"
    number_format:
        decimals: 4
    # https://symfony.com/doc/current/the-fast-track/en/22-encore.html#leveraging-bootstrap
    # https://symfony.com/doc/current/form/tailwindcss.html
    form_themes: ['tailwind_2_layout.html.twig']

when@test:
    twig:
        strict_variables: true
