vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    # https://copyprogramming.com/howto/symfony2-manual-file-upload-with-vichuploaderbundle
    metadata:
        type: attribute
    mappings:
        message_tchats_upload:
            # uri_prefix: '/mws/uploads/messages/tchats'
            # uri_prefix: '%env(BASE_HREF_FULL)%/uploads/messages/tchats'
            # # Public folder with .htaccess way : (WARNING : Security...), cf :
            # # apps/mws-sf-pdf-billings/backend/public/.htaccess.upload
            # # + Will not check logged user status if no firewall rules for public folder
            # # cf : apps/mws-sf-pdf-billings/backend/config/packages/security.yaml
            # uri_prefix: '%env.base_href%/uploads/messages/tchats'
            # # PHP Secure proxy, cf : 
            # # packages/mws-moon-manager/src/Controller/MwsConfigController.php:uploadProxy
            uri_prefix: '%env.base_href%/mws/%kernel.default_locale%/mws-config/uploads/messages/tchats'
            # Change local destination upload folder :
            # apps/mws-sf-pdf-billings/backend/config/packages/mws_moon_manager.yaml:mws_moon_manager.uploadSubFolder

            upload_destination: '%kernel.project_dir%/%mws_moon_manager.uploadSubFolder%/messages/tchats'
            # namer: MWS\MoonManagerBundle\Naming\OrignalNameNamer
            namer: mws_message_tchat_upload_namer
            # directory_namer:
            #     service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
            #     options:
            #         date_time_format: 'Y/d/m'
            #         date_time_property: uploadTimestamp
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        timing_slot_thumbnail:
            uri_prefix: '%env.base_href%/mws/%kernel.default_locale%/mws-config/uploads/timings/thumbs'
            upload_destination: '%kernel.project_dir%/%mws_moon_manager.uploadSubFolder%/timings/thumbs'
            namer: mws_message_tchat_upload_namer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
