vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    # https://copyprogramming.com/howto/symfony2-manual-file-upload-with-vichuploaderbundle
    metadata:
        type: attribute
    mappings:
        message_tchats_upload:
            uri_prefix: '/uploads/messages/tchats'
            upload_destination: '%kernel.project_dir%/public/uploads/messages/tchats'
            # namer: MWS\MoonManagerBundle\Naming\OrignalNameNamer
            namer: mws_message_tchat_upload_namer
            # directory_namer:
            #     service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
            #     options:
            #         date_time_format: 'Y/d/m'
            #         date_time_property: uploadTimestamp
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
