parameters:
    app.supported_locales: 'fr|en'
    # https://symfony.com/blog/new-in-symfony-4-3-default-and-trim-env-var-processors
    # https://stackoverflow.com/questions/50326366/set-a-default-environment-variable-in-symfony
    env(CONFIG_BCKUP_MAX_UPLOAD_SIZE): '21 Mo'
    # Number of backup history default to NO limits (-1)
    env(CONFIG_BCKUP_MAX_STACK): -1
    # TIPS : use '%env(bool:HAVE_MWS_DEMO)%' for access to avoid error 
    #        on 'must be string' from env...
    env(HAVE_MWS_DEMO): false
    # TODO : why NO error on below param ? must be string or null ?
    # /apps/mws-sf-pdf-billings/backend/vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php:154
    env(MWS_APPS): ['plugin', 'test']

# https://stackoverflow.com/questions/61059875/controller-has-no-container-set-did-you-forget-to-define-it-as-a-service-subscr
# calls:
#     - [setContainer, ["@service_container"]]
# TIPS : Declaring the controller as autowire: true will also invisibly add the setContainer.
#        It solved the problem in my case.
services:
    # apps/mws-sf-pdf-billings/backend/vendor/endroid/qr-code-bundle/src/Resources/config/services.yaml
    # Endroid\QrCodeBundle\Controller\:
    #     resource: '../src/Controller'
    #     tags: ['controller.service_arguments']
    # Endroid\QrCodeBundle\Twig\QrCodeExtension: ~
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        # bind:
        #     # pass this value to any $projectDir argument for any service
        #     # that's created in this file (including controller arguments)
        #     string $projectDir: '%kernel.project_dir%'
        # public: true


    # MWS\MoonManagerBundle\Naming\:
    #     resource: '../src/Naming/'
    #     # https://stackoverflow.com/questions/48425043/symfony-4-service-removed-or-inlined-though-it-is-public/65355876#65355876
    #     public: true
    #     # alias: MWS\MoonManagerBundle\Naming\OrignalNameNamer.message_tchats_upload

    mws_message_tchat_upload_namer:
        class: MWS\MoonManagerBundle\Naming\OrignalNameNamer
        # https://stackoverflow.com/questions/48425043/symfony-4-service-removed-or-inlined-though-it-is-public/65355876#65355876
        public: true
        # alias: MWS\MoonManagerBundle\Naming\OrignalNameNamer.message_tchats_upload

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    MWS\MoonManagerBundle\:
        resource: '../src/'
        exclude:
          - '../src/DependencyInjection/'
          - '../src/Entity/'
          - '../src/Kernel.php'
    # MWS\MoonManagerBundle\Command\:
    #     resource: '../src/Command'
    # MWS\MoonManagerBundle\Controller\:
    #     resource: '../src/Controller'
    #     tags: ['controller.service_arguments']
    # MWS\MoonManagerBundle\Repository\:
    #     resource: '../src/Repository'
    #     tags: ['doctrine.repository_service']
    # MWS\MoonManagerBundle\Form\:
    #     resource: '../src/Form'
    # MWS\MoonManagerBundle\Security\:
    #     resource: '../src/Security'
    # MWS\MoonManagerBundle\EventSubscriber\:
    #     resource: '../src/EventSubscriber'
    #     tags:
    #       # - {name: kernel.event_listener, event: kernel.exception,}
    #       - {name: kernel.event_listener,}

    # Remove PHP warnings like translation.extractor.php is depreciated :
    # TODO : remove this hack and look for package dependencies version upgrades (should have miss some package upgrades ?)
    translation.extractor.php: "@translation.extractor.php_ast"

# controllers:
#   resource: ../src/src/Controller/
#   type: annotation

# DEFAULT service file :
# # This file is the entry point to configure your own services.
# # Files in the packages/ subdirectory configure your dependencies.

# # Put parameters here that don't need to change on each machine where the app is deployed
# # https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
# parameters:

# services:
#     # default configuration for services in *this* file
#     _defaults:
#         autowire: true      # Automatically injects dependencies in your services.
#         autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

#     # makes classes in src/ available to be used as services
#     # this creates a service per class whose id is the fully-qualified class name
#     App\:
#         resource: '../src/'
#         exclude:
#             - '../src/DependencyInjection/'
#             - '../src/Entity/'
#             - '../src/Kernel.php'

#     # add more service definitions when explicit configuration is needed
#     # please note that last definitions always *replace* previous ones
