#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# https://symfony.com/doc/5.4/the-fast-track/en/28-intl.html
# https://symfony.com/doc/4.1/routing/redirect_in_config.html
home_default_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /fr
        permanent: false
        keepQueryParams: true
        keepRequestMethod: true
