# // https://stackoverflow.com/questions/72350032/extend-security-configuration-from-symfony-bundle
# // You are not allowed to define new elements for path "security.firewalls". Please define all elements for this path in one config file."
# // https://symfonycasts.com/screencast/symfony5-upgrade/final-recipe-updates
# // TODO : write recipe instead ?
security:
  # https://symfony.com/doc/current/security.html#form-login
  firewalls:
    mws_secured_area:
      # ...
      form_login:
        # "app_login" is the name of the route created previously
        login_path: mws_login
        check_path: mws_login
        enable_csrf: true
